version: 2

project_name: speedtest_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - main: ./cmd/speedtest_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os | title }}_{{ .Arch | replace \"amd64\" \"x86_64\" }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7
    use: buildx
    dockerfile: Dockerfile
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"

  - image_templates:
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  # github
  - name_template: ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}
    image_templates:
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7
  - name_template: ghcr.io/r3htanz/{{.ProjectName}}:latest
    image_templates:
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
      - ghcr.io/r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7

  # dockerhub
  - name_template: r3htanz/{{.ProjectName}}:v{{ .Version }}
    image_templates:
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7
  - name_template: r3htanz/{{.ProjectName}}:latest
    image_templates:
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-amd64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm64
      - r3htanz/{{.ProjectName}}:v{{ .Version }}-arm7
