name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Check Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.17'  # Optional: Passe an deine Go-Version an

      - name: Verify dependencies
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Build project
        run: go build -v ./...
